dependencies:
  - docker

executionClients:
  - nethermind
  - geth

consensusClients:
  - lighthouse
  - lodestar
  - prysm
  - teku
  - nimbus
 
validatorClients:
  - lighthouse
  - lodestar
  - prysm
  - teku
  - nimbus

logs:
  logLevel: debug